#ifndef ALPHARTOS_CONFIG_H
#define ALPHARTOS_CONFIG_H

#ifndef ARTOS_CFG_USE_C_DYNAMIC_MEM
#define ARTOS_CFG_USE_C_DYNAMIC_MEM 0
#endif // #ifndef ARTOS_CFG_USE_C_DYNAMIC_MEM

#ifndef ARTOS_NUM_EVENT_SERVICES
#define ARTOS_NUM_EVENT_SERVICES 16
#endif // #ifndef ARTOS_NUM_EVENT_SERVICES

#ifndef ARTOS_RUNTIME_CHECK_ARGS
#define ARTOS_RUNTIME_CHECK_ARGS 1
#endif // #ifndef ARTOS_RUNTIME_CHECK_ARGS

#ifndef ARTOS_THREAD_STACK_SIZE
#define ARTOS_THREAD_STACK_SIZE 0x00000400
#endif // #ifndef ARTOS_THREAD_STACK_SIZE

#endif // #ifndef ALPHARTOS_CONFIG_H
