#ifndef ALPHARTOS_CONFIG_H
#define ALPHARTOS_CONFIG_H

#ifndef ARTOS_CFG_USE_C_DYNAMIC_MEM
#define ARTOS_CFG_USE_C_DYNAMIC_MEM 0
#endif // #ifndef ARTOS_CFG_USE_C_DYNAMIC_MEM

#ifndef ARTOS_NUM_EVENT_SERVICES
#define ARTOS_NUM_EVENT_SERVICES 16
#endif // #ifndef ARTOS_NUM_EVENT_SERVICES

#endif // #ifndef ALPHARTOS_CONFIG_H
